# Generated by Django 2.2.2 on 2019-06-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AceInvestors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=100)),
                ('stock_no', models.CharField(max_length=100)),
                ('investor_summary', models.TextField()),
                ('profile_link', models.CharField(max_length=200)),
            ],
        ),
    ]
