# Generated by Django 2.2.2 on 2019-06-13 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aceinvestors', '0002_auto_20190613_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceinvestor',
            name='image_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
