# Generated by Django 2.2.2 on 2019-06-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceinvestors', '0003_aceinvestor_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RakeshJhunjhnwalaPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_symbol', models.CharField(max_length=100)),
                ('total_quantity_held', models.CharField(max_length=100)),
                ('Holding_percent', models.CharField(max_length=100)),
                ('Change_last_quarter', models.CharField(max_length=100)),
            ],
        ),
    ]
