# Generated by Django 2.2.2 on 2019-07-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aceinvestors', '0005_akashbhanshali_anilkumargoel_ashishkacholia_dollykhanna_mohnishpabrai_nemishshah_vijaykedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_date', models.CharField(max_length=100)),
                ('security_code', models.CharField(max_length=1000000)),
                ('company_symbol', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=100)),
                ('deal_type', models.CharField(max_length=2)),
                ('quantity', models.CharField(max_length=1000000)),
                ('price', models.FloatField()),
            ],
        ),
    ]
