# Generated by Django 2.2.2 on 2019-06-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('theme_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('trend', models.CharField(max_length=200)),
                ('explore', models.CharField(max_length=200)),
            ],
        ),
    ]
