# Generated by Django 2.2.2 on 2019-06-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsestocks',
            name='FaceValue',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bsestocks',
            name='SecurityCode',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='nsestocks',
            name='FaceValue',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nsestocks',
            name='MarketLot',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nsestocks',
            name='PaidUpValue',
            field=models.CharField(max_length=20),
        ),
    ]
